export type Operation = "convert" | "merge" | "split" | "compress" | "ocr";

export interface Tool {
  slug: string;           // URL path: /pdf_to_word
  name: string;           // Display name
  description: string;    // Card description
  pageTitle: string;      // H1 on the tool page
  pageSubtitle: string;   // Subtitle on the tool page
  category: Category;
  iconBg: string;         // Tailwind background class for icon
  iconColor: string;      // Tailwind text/stroke class
  iconType: IconType;     // Which SVG shape to render
  acceptedMime: string;   // e.g. "application/pdf"
  acceptedLabel: string;  // e.g. "PDF"
  targetFormat: string;   // "docx", "pdf", etc.
  operation: Operation;
  active: boolean;        // false = "coming soon"
}

export type IconType =
  | "merge" | "split" | "compress" | "repair" | "ocr"
  | "img_to_pdf" | "word_to_pdf" | "ppt_to_pdf" | "xls_to_pdf" | "html_to_pdf"
  | "pdf_to_img" | "pdf_to_word" | "pdf_to_ppt" | "pdf_to_xls" | "pdf_to_pdfa"
  | "rotate" | "page_num" | "watermark" | "crop" | "edit"
  | "unlock" | "protect" | "sign" | "redact" | "compare"
  | "ai" | "translate" | "remove_pages" | "extract" | "organize" | "scan";

export type Category =
  | "organize_pdf"
  | "optimize_pdf"
  | "convert_to_pdf"
  | "convert_from_pdf"
  | "edit_pdf"
  | "pdf_security"
  | "pdf_intelligence";

export const CATEGORY_LABELS: Record<Category, string> = {
  organize_pdf: "ORGANIZE PDF",
  optimize_pdf: "OPTIMIZE PDF",
  convert_to_pdf: "CONVERT TO PDF",
  convert_from_pdf: "CONVERT FROM PDF",
  edit_pdf: "EDIT PDF",
  pdf_security: "PDF SECURITY",
  pdf_intelligence: "PDF INTELLIGENCE",
};

export const tools: Tool[] = [
  // ── ORGANIZE PDF ─────────────────────────────────────────────
  {
    slug: "merge_pdf",
    name: "Merge PDF",
    description: "Combine PDFs in the order you want with the easiest PDF merger available.",
    pageTitle: "Merge PDF files",
    pageSubtitle: "Combine PDFs in the order you want with the easiest PDF merger available.",
    category: "organize_pdf",
    iconBg: "bg-[#FF6B35]",
    iconColor: "text-white",
    iconType: "merge",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "merge",
    active: true,
  },
  {
    slug: "split_pdf",
    name: "Split PDF",
    description: "Separate one page or a whole set for easy conversion into independent PDF files.",
    pageTitle: "Split a PDF file",
    pageSubtitle: "Separate one page or a whole set for easy conversion into independent PDF files.",
    category: "organize_pdf",
    iconBg: "bg-[#FF6B35]",
    iconColor: "text-white",
    iconType: "split",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "split",
    active: true,
  },
  {
    slug: "remove_pages",
    name: "Remove pages",
    description: "Delete one or several pages from your PDF with ease and flexibility.",
    pageTitle: "Remove PDF pages",
    pageSubtitle: "Delete one or several pages from your PDF with ease and flexibility.",
    category: "organize_pdf",
    iconBg: "bg-[#FF6B35]",
    iconColor: "text-white",
    iconType: "remove_pages",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "split",
    active: false,
  },
  {
    slug: "extract_pages",
    name: "Extract pages",
    description: "Extract specific pages from a PDF and save them as a new document.",
    pageTitle: "Extract PDF pages",
    pageSubtitle: "Extract specific pages from a PDF and save them as a new document.",
    category: "organize_pdf",
    iconBg: "bg-[#FF6B35]",
    iconColor: "text-white",
    iconType: "extract",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "split",
    active: false,
  },
  {
    slug: "organize_pdf",
    name: "Organize PDF",
    description: "Sort, add or delete pages of your PDF — all in a visual, easy editor.",
    pageTitle: "Organize PDF pages",
    pageSubtitle: "Sort, add or delete pages of your PDF — all in a visual, easy editor.",
    category: "organize_pdf",
    iconBg: "bg-[#FF6B35]",
    iconColor: "text-white",
    iconType: "organize",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "split",
    active: false,
  },
  {
    slug: "scan_to_pdf",
    name: "Scan to PDF",
    description: "Capture documents and photos with your mobile and convert them to PDF.",
    pageTitle: "Scan to PDF",
    pageSubtitle: "Capture documents and photos with your mobile and convert them to PDF.",
    category: "organize_pdf",
    iconBg: "bg-[#FF6B35]",
    iconColor: "text-white",
    iconType: "scan",
    acceptedMime: "image/*",
    acceptedLabel: "Image",
    targetFormat: "pdf",
    operation: "convert",
    active: false,
  },
  // ── OPTIMIZE PDF ─────────────────────────────────────────────
  {
    slug: "compress_pdf",
    name: "Compress PDF",
    description: "Reduce file size while optimising for maximal PDF quality.",
    pageTitle: "Compress a PDF file",
    pageSubtitle: "Reduce file size while optimising for maximal PDF quality.",
    category: "optimize_pdf",
    iconBg: "bg-[#67C52E]",
    iconColor: "text-white",
    iconType: "compress",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: true,
  },
  {
    slug: "repair_pdf",
    name: "Repair PDF",
    description: "Repair and recover content from a corrupt or damaged PDF.",
    pageTitle: "Repair a PDF file",
    pageSubtitle: "Repair and recover content from a corrupt or damaged PDF.",
    category: "optimize_pdf",
    iconBg: "bg-[#67C52E]",
    iconColor: "text-white",
    iconType: "repair",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "ocr_pdf",
    name: "OCR PDF",
    description: "Make your PDF searchable. Supports 40+ languages powered by Tesseract.",
    pageTitle: "OCR PDF — Make it searchable",
    pageSubtitle: "Make your PDF searchable. Supports 40+ languages powered by Tesseract.",
    category: "optimize_pdf",
    iconBg: "bg-[#67C52E]",
    iconColor: "text-white",
    iconType: "ocr",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "ocr",
    active: true,
  },
  // ── CONVERT TO PDF ───────────────────────────────────────────
  {
    slug: "jpg_to_pdf",
    name: "JPG to PDF",
    description: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.",
    pageTitle: "Convert JPG to PDF",
    pageSubtitle: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.",
    category: "convert_to_pdf",
    iconBg: "bg-[#7E57C2]",
    iconColor: "text-white",
    iconType: "img_to_pdf",
    acceptedMime: "image/jpeg,image/png",
    acceptedLabel: "JPG / PNG",
    targetFormat: "pdf",
    operation: "convert",
    active: false,
  },
  {
    slug: "word_to_pdf",
    name: "Word to PDF",
    description: "Make DOC and DOCX files easy to read by converting them to PDF.",
    pageTitle: "Convert Word to PDF",
    pageSubtitle: "Make DOC and DOCX files easy to read by converting them to PDF.",
    category: "convert_to_pdf",
    iconBg: "bg-[#2A5699]",
    iconColor: "text-white",
    iconType: "word_to_pdf",
    acceptedMime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword",
    acceptedLabel: "DOCX / DOC",
    targetFormat: "pdf",
    operation: "convert",
    active: true,
  },
  {
    slug: "powerpoint_to_pdf",
    name: "PowerPoint to PDF",
    description: "Make PPT and PPTX slideshows easy to view by converting them to PDF.",
    pageTitle: "Convert PowerPoint to PDF",
    pageSubtitle: "Make PPT and PPTX slideshows easy to view by converting them to PDF.",
    category: "convert_to_pdf",
    iconBg: "bg-[#C0392B]",
    iconColor: "text-white",
    iconType: "ppt_to_pdf",
    acceptedMime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    acceptedLabel: "PPTX / PPT",
    targetFormat: "pdf",
    operation: "convert",
    active: true,
  },
  {
    slug: "excel_to_pdf",
    name: "Excel to PDF",
    description: "Make EXCEL spreadsheets easy to read by converting them to PDF.",
    pageTitle: "Convert Excel to PDF",
    pageSubtitle: "Make EXCEL spreadsheets easy to read by converting them to PDF.",
    category: "convert_to_pdf",
    iconBg: "bg-[#1E7145]",
    iconColor: "text-white",
    iconType: "xls_to_pdf",
    acceptedMime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    acceptedLabel: "XLSX / XLS",
    targetFormat: "pdf",
    operation: "convert",
    active: true,
  },
  {
    slug: "html_to_pdf",
    name: "HTML to PDF",
    description: "Convert webpages in HTML to PDF. Copy and paste the URL of the page you want.",
    pageTitle: "Convert HTML to PDF",
    pageSubtitle: "Convert webpages in HTML to PDF. Copy and paste the URL of the page you want.",
    category: "convert_to_pdf",
    iconBg: "bg-[#E67E22]",
    iconColor: "text-white",
    iconType: "html_to_pdf",
    acceptedMime: "text/html",
    acceptedLabel: "HTML",
    targetFormat: "pdf",
    operation: "convert",
    active: false,
  },
  // ── CONVERT FROM PDF ─────────────────────────────────────────
  {
    slug: "pdf_to_jpg",
    name: "PDF to JPG",
    description: "Convert each PDF page into a JPG or extract all images contained in a PDF.",
    pageTitle: "Convert PDF to JPG",
    pageSubtitle: "Convert each PDF page into a JPG or extract all images contained in a PDF.",
    category: "convert_from_pdf",
    iconBg: "bg-[#F39C12]",
    iconColor: "text-white",
    iconType: "pdf_to_img",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "jpg",
    operation: "convert",
    active: true,
  },
  {
    slug: "pdf_to_word",
    name: "PDF to Word",
    description: "Easily convert your PDF files into easy to edit DOC and DOCX documents.",
    pageTitle: "PDF to WORD Converter",
    pageSubtitle: "Convert your PDF to WORD documents with incredible accuracy.",
    category: "convert_from_pdf",
    iconBg: "bg-[#2A5699]",
    iconColor: "text-white",
    iconType: "pdf_to_word",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "docx",
    operation: "convert",
    active: true,
  },
  {
    slug: "pdf_to_powerpoint",
    name: "PDF to PowerPoint",
    description: "Turn your PDF files into easy to edit PPT and PPTX slideshows.",
    pageTitle: "PDF to PowerPoint Converter",
    pageSubtitle: "Turn your PDF files into easy to edit PPT and PPTX slideshows.",
    category: "convert_from_pdf",
    iconBg: "bg-[#C0392B]",
    iconColor: "text-white",
    iconType: "pdf_to_ppt",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pptx",
    operation: "convert",
    active: false,
  },
  {
    slug: "pdf_to_excel",
    name: "PDF to Excel",
    description: "Pull data straight from PDFs into Excel spreadsheets in a few short seconds.",
    pageTitle: "PDF to Excel Converter",
    pageSubtitle: "Pull data straight from PDFs into Excel spreadsheets in a few short seconds.",
    category: "convert_from_pdf",
    iconBg: "bg-[#1E7145]",
    iconColor: "text-white",
    iconType: "pdf_to_xls",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "xlsx",
    operation: "convert",
    active: false,
  },
  {
    slug: "pdf_to_pdfa",
    name: "PDF to PDF/A",
    description: "Transform your PDF to PDF/A, the ISO-standardised version of PDF for archiving.",
    pageTitle: "PDF to PDF/A Converter",
    pageSubtitle: "Transform your PDF to PDF/A, the ISO-standardised version of PDF for archiving.",
    category: "convert_from_pdf",
    iconBg: "bg-[#E2201C]",
    iconColor: "text-white",
    iconType: "pdf_to_pdfa",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  // ── EDIT PDF ─────────────────────────────────────────────────
  {
    slug: "rotate_pdf",
    name: "Rotate PDF",
    description: "Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once.",
    pageTitle: "Rotate PDF pages",
    pageSubtitle: "Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once.",
    category: "edit_pdf",
    iconBg: "bg-[#AB47BC]",
    iconColor: "text-white",
    iconType: "rotate",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "add_page_numbers",
    name: "Add page numbers",
    description: "Add page numbers into PDFs with ease. Choose your positions and typography.",
    pageTitle: "Add page numbers to PDF",
    pageSubtitle: "Add page numbers into PDFs with ease. Choose your positions and typography.",
    category: "edit_pdf",
    iconBg: "bg-[#AB47BC]",
    iconColor: "text-white",
    iconType: "page_num",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "add_watermark",
    name: "Add watermark",
    description: "Stamp an image or text over your PDF in seconds. Choose the typography and transparency.",
    pageTitle: "Add watermark to PDF",
    pageSubtitle: "Stamp an image or text over your PDF in seconds. Choose the typography and transparency.",
    category: "edit_pdf",
    iconBg: "bg-[#AB47BC]",
    iconColor: "text-white",
    iconType: "watermark",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "crop_pdf",
    name: "Crop PDF",
    description: "Crop PDF pages. Change the page size of your PDF documents easily.",
    pageTitle: "Crop PDF pages",
    pageSubtitle: "Crop PDF pages. Change the page size of your PDF documents easily.",
    category: "edit_pdf",
    iconBg: "bg-[#AB47BC]",
    iconColor: "text-white",
    iconType: "crop",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "edit_pdf",
    name: "Edit PDF",
    description: "Add text, images, shapes or freehand annotations to a PDF document.",
    pageTitle: "Edit a PDF file",
    pageSubtitle: "Add text, images, shapes or freehand annotations to a PDF document.",
    category: "edit_pdf",
    iconBg: "bg-[#AB47BC]",
    iconColor: "text-white",
    iconType: "edit",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  // ── PDF SECURITY ─────────────────────────────────────────────
  {
    slug: "unlock_pdf",
    name: "Unlock PDF",
    description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    pageTitle: "Unlock PDF files",
    pageSubtitle: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    category: "pdf_security",
    iconBg: "bg-[#1E88E5]",
    iconColor: "text-white",
    iconType: "unlock",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "protect_pdf",
    name: "Protect PDF",
    description: "Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.",
    pageTitle: "Protect a PDF file",
    pageSubtitle: "Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.",
    category: "pdf_security",
    iconBg: "bg-[#1E88E5]",
    iconColor: "text-white",
    iconType: "protect",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "sign_pdf",
    name: "Sign PDF",
    description: "Sign yourself or request electronic signatures from others.",
    pageTitle: "Sign a PDF document",
    pageSubtitle: "Sign yourself or request electronic signatures from others.",
    category: "pdf_security",
    iconBg: "bg-[#1E88E5]",
    iconColor: "text-white",
    iconType: "sign",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "redact_pdf",
    name: "Redact PDF",
    description: "Permanently delete sensitive information from your PDF documents.",
    pageTitle: "Redact PDF content",
    pageSubtitle: "Permanently delete sensitive information from your PDF documents.",
    category: "pdf_security",
    iconBg: "bg-[#1E88E5]",
    iconColor: "text-white",
    iconType: "redact",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  {
    slug: "compare_pdf",
    name: "Compare PDF",
    description: "Show a side by side comparison of two PDFs and see the differences clearly.",
    pageTitle: "Compare PDF files",
    pageSubtitle: "Show a side by side comparison of two PDFs and see the differences clearly.",
    category: "pdf_security",
    iconBg: "bg-[#1E88E5]",
    iconColor: "text-white",
    iconType: "compare",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "compress",
    active: false,
  },
  // ── PDF INTELLIGENCE ─────────────────────────────────────────
  {
    slug: "ai_summarizer",
    name: "AI Summarizer",
    description: "Extract the most important information from your PDFs with AI-powered summarization.",
    pageTitle: "AI PDF Summarizer",
    pageSubtitle: "Extract the most important information from your PDFs with AI-powered summarization.",
    category: "pdf_intelligence",
    iconBg: "bg-[#5C6BC0]",
    iconColor: "text-white",
    iconType: "ai",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "ocr",
    active: false,
  },
  {
    slug: "translate_pdf",
    name: "Translate PDF",
    description: "Translate your PDF documents into any language. Fast and accurate.",
    pageTitle: "Translate a PDF",
    pageSubtitle: "Translate your PDF documents into any language. Fast and accurate.",
    category: "pdf_intelligence",
    iconBg: "bg-[#5C6BC0]",
    iconColor: "text-white",
    iconType: "translate",
    acceptedMime: "application/pdf",
    acceptedLabel: "PDF",
    targetFormat: "pdf",
    operation: "ocr",
    active: false,
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: Category): Tool[] {
  return tools.filter((t) => t.category === category);
}

export const ALL_CATEGORIES = Object.keys(CATEGORY_LABELS) as Category[];
